version: '3.9'

services:
    app:
        build:
            context: ./php
        container_name: backend
        working_dir: /var/www/html
        volumes:
            - ../backend:/var/www/html
        ports:
            - "9000:9000"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:base64:w5QNiO6wgZAERtV0U0EpKx6QGW3u87ACHU67hk1+sXg=
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: diplom_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: diplom
            MYSQL_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
